### ISSUE TITLE
Setup instructions don't work:

### ISSUE THREAD

**Issue by kingio** [wrouesnel/docker-squid4#4]
Using the readme's command:

    docker run -it -p 3128:127.0.0.1:3128 --rm \
    >     -v /srv/squid/cache:/var/cache/squid4 \
    >     -v /etc/ssl/certs:/etc/ssl/certs:ro \ 
    docker: Invalid ip address: 3128.
    See 'docker run --help'.

Trying to fix it:
   
    docker run -it -p 3128:3128 squid
    Unable to find image 'squid:latest' locally
    docker: Error response from daemon: pull access denied for squid, repository does not exist or may     require 'docker login'.

¿Could you improve the instructions?

**Comment by Gerkiz** [comment]
Remove the spaces each line after `\`
And at the bottom add:
`wrouesnel/docker-squid4` (instead of squid)
